# Generated by Django 4.2.6 on 2023-11-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BuddyList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buddy", models.TextField()),
                ("num", models.TextField()),
                ("pin", models.BooleanField(verbose_name=True)),
            ],
        ),
    ]
